### ISSUE TITLE
Glowing armor still crashes the client

### ISSUE THREAD

**Issue by Moholmarn** [Chuunkyz/Benchmark-1.17.1#15] opened 2021-11-14 11:22 UTC
Might be related to issue #9 

https://pastebin.com/T35gsVWJ

**Comment by Chuunkyz** [comment] 2021-11-14 11:23
that's due to eldritch mobs, and seems like the issue is still not fixed...

**Comment by Moholmarn** [comment] 2021-11-14 13:19
Saw your ticket on their issue tracker, hopefully they can get it fixed.

**Comment by Chuunkyz** [comment] 2021-11-23 20:24
fixed in the next update ;)

**Closed as completed by Chuunkyz** 2021-11-23 20:24 UTC

**Comment by Moholmarn** [comment] 2021-11-24 12:14
Nice!
